// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `collection.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:FoldersRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FoldersRow {
    // message fields
    // @@protoc_insertion_point(field:FoldersRow.folder_id)
    pub folder_id: i64,
    // @@protoc_insertion_point(field:FoldersRow.parent_folder_id)
    pub parent_folder_id: i64,
    // @@protoc_insertion_point(field:FoldersRow.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:FoldersRow.folder_type)
    pub folder_type: i32,
    // @@protoc_insertion_point(field:FoldersRow.avatar_picture_id)
    pub avatar_picture_id: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:FoldersRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FoldersRow {
    fn default() -> &'a FoldersRow {
        <FoldersRow as ::protobuf::Message>::default_instance()
    }
}

impl FoldersRow {
    pub fn new() -> FoldersRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "folder_id",
            |m: &FoldersRow| { &m.folder_id },
            |m: &mut FoldersRow| { &mut m.folder_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "parent_folder_id",
            |m: &FoldersRow| { &m.parent_folder_id },
            |m: &mut FoldersRow| { &mut m.parent_folder_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &FoldersRow| { &m.name },
            |m: &mut FoldersRow| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "folder_type",
            |m: &FoldersRow| { &m.folder_type },
            |m: &mut FoldersRow| { &mut m.folder_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "avatar_picture_id",
            |m: &FoldersRow| { &m.avatar_picture_id },
            |m: &mut FoldersRow| { &mut m.avatar_picture_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FoldersRow>(
            "FoldersRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FoldersRow {
    const NAME: &'static str = "FoldersRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.folder_id = is.read_int64()?;
                },
                16 => {
                    self.parent_folder_id = is.read_int64()?;
                },
                26 => {
                    self.name = is.read_string()?;
                },
                32 => {
                    self.folder_type = is.read_int32()?;
                },
                40 => {
                    self.avatar_picture_id = ::std::option::Option::Some(is.read_int64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.folder_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.folder_id);
        }
        if self.parent_folder_id != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.parent_folder_id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.name);
        }
        if self.folder_type != 0 {
            my_size += ::protobuf::rt::int32_size(4, self.folder_type);
        }
        if let Some(v) = self.avatar_picture_id {
            my_size += ::protobuf::rt::int64_size(5, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.folder_id != 0 {
            os.write_int64(1, self.folder_id)?;
        }
        if self.parent_folder_id != 0 {
            os.write_int64(2, self.parent_folder_id)?;
        }
        if !self.name.is_empty() {
            os.write_string(3, &self.name)?;
        }
        if self.folder_type != 0 {
            os.write_int32(4, self.folder_type)?;
        }
        if let Some(v) = self.avatar_picture_id {
            os.write_int64(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FoldersRow {
        FoldersRow::new()
    }

    fn clear(&mut self) {
        self.folder_id = 0;
        self.parent_folder_id = 0;
        self.name.clear();
        self.folder_type = 0;
        self.avatar_picture_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FoldersRow {
        static instance: FoldersRow = FoldersRow {
            folder_id: 0,
            parent_folder_id: 0,
            name: ::std::string::String::new(),
            folder_type: 0,
            avatar_picture_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FoldersRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FoldersRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FoldersRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FoldersRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:MusicItemsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MusicItemsRow {
    // message fields
    // @@protoc_insertion_point(field:MusicItemsRow.music_item_id)
    pub music_item_id: i64,
    // @@protoc_insertion_point(field:MusicItemsRow.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:MusicItemsRow.folder_id)
    pub folder_id: i64,
    // special fields
    // @@protoc_insertion_point(special_field:MusicItemsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MusicItemsRow {
    fn default() -> &'a MusicItemsRow {
        <MusicItemsRow as ::protobuf::Message>::default_instance()
    }
}

impl MusicItemsRow {
    pub fn new() -> MusicItemsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "music_item_id",
            |m: &MusicItemsRow| { &m.music_item_id },
            |m: &mut MusicItemsRow| { &mut m.music_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &MusicItemsRow| { &m.name },
            |m: &mut MusicItemsRow| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "folder_id",
            |m: &MusicItemsRow| { &m.folder_id },
            |m: &mut MusicItemsRow| { &mut m.folder_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MusicItemsRow>(
            "MusicItemsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MusicItemsRow {
    const NAME: &'static str = "MusicItemsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.music_item_id = is.read_int64()?;
                },
                18 => {
                    self.name = is.read_string()?;
                },
                24 => {
                    self.folder_id = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.music_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.music_item_id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if self.folder_id != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.folder_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.music_item_id != 0 {
            os.write_int64(1, self.music_item_id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if self.folder_id != 0 {
            os.write_int64(3, self.folder_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MusicItemsRow {
        MusicItemsRow::new()
    }

    fn clear(&mut self) {
        self.music_item_id = 0;
        self.name.clear();
        self.folder_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MusicItemsRow {
        static instance: MusicItemsRow = MusicItemsRow {
            music_item_id: 0,
            name: ::std::string::String::new(),
            folder_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MusicItemsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MusicItemsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MusicItemsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MusicItemsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:LyricsItemsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LyricsItemsRow {
    // message fields
    // @@protoc_insertion_point(field:LyricsItemsRow.lyrics_item_id)
    pub lyrics_item_id: i64,
    // @@protoc_insertion_point(field:LyricsItemsRow.music_item_id)
    pub music_item_id: i64,
    // @@protoc_insertion_point(field:LyricsItemsRow.lang_code)
    pub lang_code: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:LyricsItemsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LyricsItemsRow {
    fn default() -> &'a LyricsItemsRow {
        <LyricsItemsRow as ::protobuf::Message>::default_instance()
    }
}

impl LyricsItemsRow {
    pub fn new() -> LyricsItemsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "lyrics_item_id",
            |m: &LyricsItemsRow| { &m.lyrics_item_id },
            |m: &mut LyricsItemsRow| { &mut m.lyrics_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "music_item_id",
            |m: &LyricsItemsRow| { &m.music_item_id },
            |m: &mut LyricsItemsRow| { &mut m.music_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "lang_code",
            |m: &LyricsItemsRow| { &m.lang_code },
            |m: &mut LyricsItemsRow| { &mut m.lang_code },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LyricsItemsRow>(
            "LyricsItemsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LyricsItemsRow {
    const NAME: &'static str = "LyricsItemsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.lyrics_item_id = is.read_int64()?;
                },
                16 => {
                    self.music_item_id = is.read_int64()?;
                },
                26 => {
                    self.lang_code = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.lyrics_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.lyrics_item_id);
        }
        if self.music_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.music_item_id);
        }
        if !self.lang_code.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.lang_code);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.lyrics_item_id != 0 {
            os.write_int64(1, self.lyrics_item_id)?;
        }
        if self.music_item_id != 0 {
            os.write_int64(2, self.music_item_id)?;
        }
        if !self.lang_code.is_empty() {
            os.write_string(3, &self.lang_code)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LyricsItemsRow {
        LyricsItemsRow::new()
    }

    fn clear(&mut self) {
        self.lyrics_item_id = 0;
        self.music_item_id = 0;
        self.lang_code.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LyricsItemsRow {
        static instance: LyricsItemsRow = LyricsItemsRow {
            lyrics_item_id: 0,
            music_item_id: 0,
            lang_code: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LyricsItemsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LyricsItemsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LyricsItemsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LyricsItemsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:PictureItemsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PictureItemsRow {
    // message fields
    // @@protoc_insertion_point(field:PictureItemsRow.picture_item_id)
    pub picture_item_id: i64,
    // @@protoc_insertion_point(field:PictureItemsRow.extension)
    pub extension: ::std::string::String,
    // @@protoc_insertion_point(field:PictureItemsRow.folder_id)
    pub folder_id: i64,
    // special fields
    // @@protoc_insertion_point(special_field:PictureItemsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PictureItemsRow {
    fn default() -> &'a PictureItemsRow {
        <PictureItemsRow as ::protobuf::Message>::default_instance()
    }
}

impl PictureItemsRow {
    pub fn new() -> PictureItemsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "picture_item_id",
            |m: &PictureItemsRow| { &m.picture_item_id },
            |m: &mut PictureItemsRow| { &mut m.picture_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "extension",
            |m: &PictureItemsRow| { &m.extension },
            |m: &mut PictureItemsRow| { &mut m.extension },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "folder_id",
            |m: &PictureItemsRow| { &m.folder_id },
            |m: &mut PictureItemsRow| { &mut m.folder_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PictureItemsRow>(
            "PictureItemsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PictureItemsRow {
    const NAME: &'static str = "PictureItemsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.picture_item_id = is.read_int64()?;
                },
                18 => {
                    self.extension = is.read_string()?;
                },
                24 => {
                    self.folder_id = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.picture_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.picture_item_id);
        }
        if !self.extension.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.extension);
        }
        if self.folder_id != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.folder_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.picture_item_id != 0 {
            os.write_int64(1, self.picture_item_id)?;
        }
        if !self.extension.is_empty() {
            os.write_string(2, &self.extension)?;
        }
        if self.folder_id != 0 {
            os.write_int64(3, self.folder_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PictureItemsRow {
        PictureItemsRow::new()
    }

    fn clear(&mut self) {
        self.picture_item_id = 0;
        self.extension.clear();
        self.folder_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PictureItemsRow {
        static instance: PictureItemsRow = PictureItemsRow {
            picture_item_id: 0,
            extension: ::std::string::String::new(),
            folder_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PictureItemsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PictureItemsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PictureItemsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PictureItemsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:TagsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TagsRow {
    // message fields
    // @@protoc_insertion_point(field:TagsRow.tag_id)
    pub tag_id: i64,
    // @@protoc_insertion_point(field:TagsRow.music_item_id)
    pub music_item_id: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:TagsRow.folder_id)
    pub folder_id: ::std::option::Option<i64>,
    // @@protoc_insertion_point(field:TagsRow.tag_name)
    pub tag_name: ::std::string::String,
    // @@protoc_insertion_point(field:TagsRow.tag_value)
    pub tag_value: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:TagsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TagsRow {
    fn default() -> &'a TagsRow {
        <TagsRow as ::protobuf::Message>::default_instance()
    }
}

impl TagsRow {
    pub fn new() -> TagsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tag_id",
            |m: &TagsRow| { &m.tag_id },
            |m: &mut TagsRow| { &mut m.tag_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "music_item_id",
            |m: &TagsRow| { &m.music_item_id },
            |m: &mut TagsRow| { &mut m.music_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "folder_id",
            |m: &TagsRow| { &m.folder_id },
            |m: &mut TagsRow| { &mut m.folder_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tag_name",
            |m: &TagsRow| { &m.tag_name },
            |m: &mut TagsRow| { &mut m.tag_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tag_value",
            |m: &TagsRow| { &m.tag_value },
            |m: &mut TagsRow| { &mut m.tag_value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TagsRow>(
            "TagsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TagsRow {
    const NAME: &'static str = "TagsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.tag_id = is.read_int64()?;
                },
                16 => {
                    self.music_item_id = ::std::option::Option::Some(is.read_int64()?);
                },
                24 => {
                    self.folder_id = ::std::option::Option::Some(is.read_int64()?);
                },
                34 => {
                    self.tag_name = is.read_string()?;
                },
                42 => {
                    self.tag_value = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.tag_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.tag_id);
        }
        if let Some(v) = self.music_item_id {
            my_size += ::protobuf::rt::int64_size(2, v);
        }
        if let Some(v) = self.folder_id {
            my_size += ::protobuf::rt::int64_size(3, v);
        }
        if !self.tag_name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.tag_name);
        }
        if !self.tag_value.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.tag_value);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.tag_id != 0 {
            os.write_int64(1, self.tag_id)?;
        }
        if let Some(v) = self.music_item_id {
            os.write_int64(2, v)?;
        }
        if let Some(v) = self.folder_id {
            os.write_int64(3, v)?;
        }
        if !self.tag_name.is_empty() {
            os.write_string(4, &self.tag_name)?;
        }
        if !self.tag_value.is_empty() {
            os.write_string(5, &self.tag_value)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TagsRow {
        TagsRow::new()
    }

    fn clear(&mut self) {
        self.tag_id = 0;
        self.music_item_id = ::std::option::Option::None;
        self.folder_id = ::std::option::Option::None;
        self.tag_name.clear();
        self.tag_value.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TagsRow {
        static instance: TagsRow = TagsRow {
            tag_id: 0,
            music_item_id: ::std::option::Option::None,
            folder_id: ::std::option::Option::None,
            tag_name: ::std::string::String::new(),
            tag_value: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TagsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TagsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TagsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TagsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:MusicSrcFilesRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MusicSrcFilesRow {
    // message fields
    // @@protoc_insertion_point(field:MusicSrcFilesRow.src_file_id)
    pub src_file_id: i64,
    // @@protoc_insertion_point(field:MusicSrcFilesRow.music_item_id)
    pub music_item_id: i64,
    // @@protoc_insertion_point(field:MusicSrcFilesRow.source_type)
    pub source_type: i32,
    // @@protoc_insertion_point(field:MusicSrcFilesRow.path)
    pub path: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:MusicSrcFilesRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MusicSrcFilesRow {
    fn default() -> &'a MusicSrcFilesRow {
        <MusicSrcFilesRow as ::protobuf::Message>::default_instance()
    }
}

impl MusicSrcFilesRow {
    pub fn new() -> MusicSrcFilesRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "src_file_id",
            |m: &MusicSrcFilesRow| { &m.src_file_id },
            |m: &mut MusicSrcFilesRow| { &mut m.src_file_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "music_item_id",
            |m: &MusicSrcFilesRow| { &m.music_item_id },
            |m: &mut MusicSrcFilesRow| { &mut m.music_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "source_type",
            |m: &MusicSrcFilesRow| { &m.source_type },
            |m: &mut MusicSrcFilesRow| { &mut m.source_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "path",
            |m: &MusicSrcFilesRow| { &m.path },
            |m: &mut MusicSrcFilesRow| { &mut m.path },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MusicSrcFilesRow>(
            "MusicSrcFilesRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MusicSrcFilesRow {
    const NAME: &'static str = "MusicSrcFilesRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.src_file_id = is.read_int64()?;
                },
                16 => {
                    self.music_item_id = is.read_int64()?;
                },
                24 => {
                    self.source_type = is.read_int32()?;
                },
                34 => {
                    self.path = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.src_file_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.src_file_id);
        }
        if self.music_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.music_item_id);
        }
        if self.source_type != 0 {
            my_size += ::protobuf::rt::int32_size(3, self.source_type);
        }
        if !self.path.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.path);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.src_file_id != 0 {
            os.write_int64(1, self.src_file_id)?;
        }
        if self.music_item_id != 0 {
            os.write_int64(2, self.music_item_id)?;
        }
        if self.source_type != 0 {
            os.write_int32(3, self.source_type)?;
        }
        if !self.path.is_empty() {
            os.write_string(4, &self.path)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MusicSrcFilesRow {
        MusicSrcFilesRow::new()
    }

    fn clear(&mut self) {
        self.src_file_id = 0;
        self.music_item_id = 0;
        self.source_type = 0;
        self.path.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MusicSrcFilesRow {
        static instance: MusicSrcFilesRow = MusicSrcFilesRow {
            src_file_id: 0,
            music_item_id: 0,
            source_type: 0,
            path: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MusicSrcFilesRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MusicSrcFilesRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MusicSrcFilesRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MusicSrcFilesRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:PlaylistsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PlaylistsRow {
    // message fields
    // @@protoc_insertion_point(field:PlaylistsRow.playlist_id)
    pub playlist_id: i64,
    // @@protoc_insertion_point(field:PlaylistsRow.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:PlaylistsRow.avatar_picture_id)
    pub avatar_picture_id: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:PlaylistsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PlaylistsRow {
    fn default() -> &'a PlaylistsRow {
        <PlaylistsRow as ::protobuf::Message>::default_instance()
    }
}

impl PlaylistsRow {
    pub fn new() -> PlaylistsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "playlist_id",
            |m: &PlaylistsRow| { &m.playlist_id },
            |m: &mut PlaylistsRow| { &mut m.playlist_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &PlaylistsRow| { &m.name },
            |m: &mut PlaylistsRow| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "avatar_picture_id",
            |m: &PlaylistsRow| { &m.avatar_picture_id },
            |m: &mut PlaylistsRow| { &mut m.avatar_picture_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PlaylistsRow>(
            "PlaylistsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PlaylistsRow {
    const NAME: &'static str = "PlaylistsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.playlist_id = is.read_int64()?;
                },
                18 => {
                    self.name = is.read_string()?;
                },
                24 => {
                    self.avatar_picture_id = ::std::option::Option::Some(is.read_int64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.playlist_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.playlist_id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if let Some(v) = self.avatar_picture_id {
            my_size += ::protobuf::rt::int64_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.playlist_id != 0 {
            os.write_int64(1, self.playlist_id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if let Some(v) = self.avatar_picture_id {
            os.write_int64(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PlaylistsRow {
        PlaylistsRow::new()
    }

    fn clear(&mut self) {
        self.playlist_id = 0;
        self.name.clear();
        self.avatar_picture_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PlaylistsRow {
        static instance: PlaylistsRow = PlaylistsRow {
            playlist_id: 0,
            name: ::std::string::String::new(),
            avatar_picture_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PlaylistsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PlaylistsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PlaylistsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PlaylistsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:PlaylistItemsRow)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PlaylistItemsRow {
    // message fields
    // @@protoc_insertion_point(field:PlaylistItemsRow.playlist_item_id)
    pub playlist_item_id: i64,
    // @@protoc_insertion_point(field:PlaylistItemsRow.playlist_id)
    pub playlist_id: i64,
    // @@protoc_insertion_point(field:PlaylistItemsRow.music_item_id)
    pub music_item_id: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:PlaylistItemsRow.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PlaylistItemsRow {
    fn default() -> &'a PlaylistItemsRow {
        <PlaylistItemsRow as ::protobuf::Message>::default_instance()
    }
}

impl PlaylistItemsRow {
    pub fn new() -> PlaylistItemsRow {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "playlist_item_id",
            |m: &PlaylistItemsRow| { &m.playlist_item_id },
            |m: &mut PlaylistItemsRow| { &mut m.playlist_item_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "playlist_id",
            |m: &PlaylistItemsRow| { &m.playlist_id },
            |m: &mut PlaylistItemsRow| { &mut m.playlist_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "music_item_id",
            |m: &PlaylistItemsRow| { &m.music_item_id },
            |m: &mut PlaylistItemsRow| { &mut m.music_item_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PlaylistItemsRow>(
            "PlaylistItemsRow",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PlaylistItemsRow {
    const NAME: &'static str = "PlaylistItemsRow";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.playlist_item_id = is.read_int64()?;
                },
                16 => {
                    self.playlist_id = is.read_int64()?;
                },
                24 => {
                    self.music_item_id = ::std::option::Option::Some(is.read_int64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.playlist_item_id != 0 {
            my_size += ::protobuf::rt::int64_size(1, self.playlist_item_id);
        }
        if self.playlist_id != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.playlist_id);
        }
        if let Some(v) = self.music_item_id {
            my_size += ::protobuf::rt::int64_size(3, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.playlist_item_id != 0 {
            os.write_int64(1, self.playlist_item_id)?;
        }
        if self.playlist_id != 0 {
            os.write_int64(2, self.playlist_id)?;
        }
        if let Some(v) = self.music_item_id {
            os.write_int64(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PlaylistItemsRow {
        PlaylistItemsRow::new()
    }

    fn clear(&mut self) {
        self.playlist_item_id = 0;
        self.playlist_id = 0;
        self.music_item_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PlaylistItemsRow {
        static instance: PlaylistItemsRow = PlaylistItemsRow {
            playlist_item_id: 0,
            playlist_id: 0,
            music_item_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PlaylistItemsRow {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PlaylistItemsRow").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PlaylistItemsRow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PlaylistItemsRow {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10collection.proto\"\xcf\x01\n\nFoldersRow\x12\x1b\n\tfolder_id\x18\
    \x01\x20\x01(\x03R\x08folderId\x12(\n\x10parent_folder_id\x18\x02\x20\
    \x01(\x03R\x0eparentFolderId\x12\x12\n\x04name\x18\x03\x20\x01(\tR\x04na\
    me\x12\x1f\n\x0bfolder_type\x18\x04\x20\x01(\x05R\nfolderType\x12/\n\x11\
    avatar_picture_id\x18\x05\x20\x01(\x03H\0R\x0favatarPictureId\x88\x01\
    \x01B\x14\n\x12_avatar_picture_id\"d\n\rMusicItemsRow\x12\"\n\rmusic_ite\
    m_id\x18\x01\x20\x01(\x03R\x0bmusicItemId\x12\x12\n\x04name\x18\x02\x20\
    \x01(\tR\x04name\x12\x1b\n\tfolder_id\x18\x03\x20\x01(\x03R\x08folderId\
    \"w\n\x0eLyricsItemsRow\x12$\n\x0elyrics_item_id\x18\x01\x20\x01(\x03R\
    \x0clyricsItemId\x12\"\n\rmusic_item_id\x18\x02\x20\x01(\x03R\x0bmusicIt\
    emId\x12\x1b\n\tlang_code\x18\x03\x20\x01(\tR\x08langCode\"t\n\x0fPictur\
    eItemsRow\x12&\n\x0fpicture_item_id\x18\x01\x20\x01(\x03R\rpictureItemId\
    \x12\x1c\n\textension\x18\x02\x20\x01(\tR\textension\x12\x1b\n\tfolder_i\
    d\x18\x03\x20\x01(\x03R\x08folderId\"\xc3\x01\n\x07TagsRow\x12\x15\n\x06\
    tag_id\x18\x01\x20\x01(\x03R\x05tagId\x12'\n\rmusic_item_id\x18\x02\x20\
    \x01(\x03H\0R\x0bmusicItemId\x88\x01\x01\x12\x20\n\tfolder_id\x18\x03\
    \x20\x01(\x03H\x01R\x08folderId\x88\x01\x01\x12\x19\n\x08tag_name\x18\
    \x04\x20\x01(\tR\x07tagName\x12\x1b\n\ttag_value\x18\x05\x20\x01(\tR\x08\
    tagValueB\x10\n\x0e_music_item_idB\x0c\n\n_folder_id\"\x8b\x01\n\x10Musi\
    cSrcFilesRow\x12\x1e\n\x0bsrc_file_id\x18\x01\x20\x01(\x03R\tsrcFileId\
    \x12\"\n\rmusic_item_id\x18\x02\x20\x01(\x03R\x0bmusicItemId\x12\x1f\n\
    \x0bsource_type\x18\x03\x20\x01(\x05R\nsourceType\x12\x12\n\x04path\x18\
    \x04\x20\x01(\tR\x04path\"\x8a\x01\n\x0cPlaylistsRow\x12\x1f\n\x0bplayli\
    st_id\x18\x01\x20\x01(\x03R\nplaylistId\x12\x12\n\x04name\x18\x02\x20\
    \x01(\tR\x04name\x12/\n\x11avatar_picture_id\x18\x03\x20\x01(\x03H\0R\
    \x0favatarPictureId\x88\x01\x01B\x14\n\x12_avatar_picture_id\"\x98\x01\n\
    \x10PlaylistItemsRow\x12(\n\x10playlist_item_id\x18\x01\x20\x01(\x03R\
    \x0eplaylistItemId\x12\x1f\n\x0bplaylist_id\x18\x02\x20\x01(\x03R\nplayl\
    istId\x12'\n\rmusic_item_id\x18\x03\x20\x01(\x03H\0R\x0bmusicItemId\x88\
    \x01\x01B\x10\n\x0e_music_item_idb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(FoldersRow::generated_message_descriptor_data());
            messages.push(MusicItemsRow::generated_message_descriptor_data());
            messages.push(LyricsItemsRow::generated_message_descriptor_data());
            messages.push(PictureItemsRow::generated_message_descriptor_data());
            messages.push(TagsRow::generated_message_descriptor_data());
            messages.push(MusicSrcFilesRow::generated_message_descriptor_data());
            messages.push(PlaylistsRow::generated_message_descriptor_data());
            messages.push(PlaylistItemsRow::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
