database:
  sqlite_config:
    # Database work mode:
    # RAM  - For debug only.
    # FILE - Normal mode.
    mode: RAM

collection:

  init: false

  # Folder containing collection template in csv files
  init_folder: "../../lappi_dataset/default_collection"

  storage: true

web_server:
  # http server
  port: 8080
  # Path to frontend folder
  static_files_path: "/usr/src/lappi/lappi_lab_ui"

