database:
  sqlite_config:
    # Database work mode:
    # RAM  - For debug only.
    # FILE - Normal mode.
    mode: RAM

collection:

  init: true

  # Folder containing collection template in csv files
  init_folder: "../lappi_dataset/default_collection"

  storage: true
