database:
  sqlite_config:
    # Database work mode:
    # RAM  - For debug only.
    # FILE - Normal mode.
    mode: FILE

collection:

  init: false

  # Folder containing collection template in csv files
  init_folder: "collection_init"
